export const PRIMARY_TAGS = [
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Mobile Developer",
  "Data Engineer",
  "Data Scientist",
  "QA Engineer",
  "Security Engineer",
  "Cloud Engineer",
  "Embedded Systems Engineer",
  "Blockchain Developer",
  "Game Developer",
  "Site Reliability Engineer (SRE)",
  "Machine Learning Engineer",
  "Software Architect",
  "Technical Lead",
  "Product Manager",
  "Systems Analyst",
  "Network Engineer",
] as const;

export const EMPLOYMENT_TYPE = [
  "Full time",
  "Part time",
  "Freelancing",
  "Contractual",
  "Volenteer",
  "Internship",
  "Temporary",
] as const;

export const SALARY = [
  "10,000 USD per year",
  "20,000 USD per year",
  "30,000 USD per year",
  "40,000 USD per year",
  "50,000 USD per year",
  "60,000 USD per year",
  "70,000 USD per year",
  "80,000 USD per year",
  "90,000 USD per year",
  "100,000 USD per year",
  "110,000 USD per year",
  "120,000 USD per year",
  "130,000 USD per year",
  "140,000 USD per year",
  "150,000 USD per year",
  "160,000 USD per year",
  "170,000 USD per year",
  "180,000 USD per year",
  "190,000 USD per year",
  "200,000 USD per year",
  "210,000 USD per year",
  "220,000 USD per year",
  "230,000 USD per year",
  "240,000 USD per year",
  "250,000 USD per year",
  "260,000 USD per year",
  "270,000 USD per year",
  "280,000 USD per year",
  "290,000 USD per year",
  "300,000 USD per year",
  "310,000 USD per year",
  "320,000 USD per year",
  "330,000 USD per year",
  "340,000 USD per year",
  "350,000 USD per year",
  "360,000 USD per year",
  "370,000 USD per year",
  "380,000 USD per year",
  "390,000 USD per year",
  "400,000 USD per year",
  "410,000 USD per year",
  "420,000 USD per year",
  "430,000 USD per year",
  "440,000 USD per year",
  "450,000 USD per year",
  "460,000 USD per year",
  "470,000 USD per year",
  "480,000 USD per year",
  "490,000 USD per year",
  "500,000 USD per year",
];

export const COUNTRIES = [
  "Worldwide",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Swaziland",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
